# Generated by Django 5.2.1 on 2025-05-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="type",
            field=models.CharField(
                choices=[
                    ("SUV", "SUV"),
                    ("sedan", "sedan"),
                    ("hatchback", "hatchback"),
                    ("coupe", "coupe"),
                ],
                default="SUV",
                max_length=15,
            ),
        ),
    ]
